name = "find-your-duo-games"
account_id = "f30fd63af7fe0a1e16fbec05a4403b3c"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2022-09-23"

[dev]
ip = "127.0.0.1"
port = 8787
local_protocol="http"
upstream_protocol="https"
